Added initial c++ code to parse logs.
Signed-off-by: Mohammad Alaggan <mohammad.nabil.h@gmail.com>

diff --git a/RUN b/RUN
--- a/RUN
+++ b/RUN
@@ -1,2 +1,13 @@
 #!/usr/bin/env bash
-sbt package && SPARK_LOCAL_IP=127.0.0.1 spark-submit --packages com.databricks:spark-csv_2.11:1.3.0 --driver-memory 25G --class Slices --master local[8] target/scala-2.11/hdp-analysis_2.11-1.0.jar
+set -e # exit immediately on error
+sbt package
+export SPARK_LOCAL_IP=127.0.0.1
+rm -rf baseline blind slices naive groups
+spark-submit --packages com.databricks:spark-csv_2.11:1.3.0 \
+						 --driver-memory 25G --class Slices --master local[8] \
+						 target/scala-2.11/hdp-analysis_2.11-1.0.jar
+cat baseline/part-* > baseline.csv
+cat blind/part-*		> blind.csv
+cat slices/part-*		> slices.csv
+cat naive/part-*		> naive.csv
+cat groups/part-*		> groups.csv
